### ISSUE TITLE
Add documentation to bulkReadRows that each batch will process the keys sequentially

### ISSUE THREAD

**Issue by igorbernstein2** [googleapis/java-bigtable#386]
ReadRows protocol requires that rows are sent in ascending key order, which implies that each key in the request must be looked up sequentially. We should make this clear in the javadocs to ensure that our customers have the correct expectations

**Comment by mgarolera** [comment]
Worth noting that the mismatch in expectations is related to performance.

There is the assumption that fetching N rows ends up being ~ N/M * max(latency of M fetches), where M is the batch size (default 100?), but it is closer to sum(latency of N fetches), specially if the rows are clearly disjoint and fall in different nodes.

This becomes very bad when the client is far from the data, as it ends leading to N round trips instead of ~N/M.
