### ISSUE TITLE
what is alternative to hbase bulkload

### ISSUE THREAD

**Issue by helanyao** [googleapis/java-bigtable#585]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

**Is your feature request related to a problem? Please describe.**
What the problem is. Example: I'm always frustrated when [...]

**Describe the solution you'd like**
We are planning to migrate from hbase to bigtable. We used bulkload to load large amount of data. The bulkload is efficient and it is able to ensure Idempotency. How to achieve the efficiency and update idempotency via bigtable? Do you have any recommendation?

**Describe alternatives you've considered**
Any alternative solutions or features you've considered.

**Additional context**
Any other context or screenshots about the feature request.

**Comment by helanyao** [comment]
Can anyone help here please?

**Comment by igorbernstein2** [comment]
cc @lichng & @vermas2012 

Currently our migration process depends on exporting HBase data as SequenceFiles. To either HDFS or GCS and running either a map reduce job or dataflow job to import the data into Bigtable.

We are currently working on a dataflow job that could import HBase snapshot files directly.

Both methods should be idempotent for mutations because the timestamps should be preserved. However Bigtable doesnt have a concept of delete markers, so we can't ensure that deletes are idempotent.

**Comment by vermas2012** [comment]
When you say "update idempotency", do you mean during the migration or post migrations (daily import jobs?). 

For migrations, recommended solution is to use dataflow import templates (HBase sequence files or HBase snapshots). These imports will be idempotent and running the import multiple times will not have any side effects (Assuming there are no other writes happening to Bigtable during the migration).
